### ISSUE TITLE
I can't get the audio to pause

### ISSUE THREAD

**Issue by OdapX** [goldfire/howler.js#1555] opened 2022-01-25 23:15 UTC
### The Problem

I'm trying to build a sort of music player web app with nextjs , now the probleme is that once I get the audio to play It doesn't pause with the pause function .

here is my code :

![code](https://user-images.githubusercontent.com/72660683/151075171-72883b87-529a-4bdd-b57d-12c7021aab2c.png)

the functions ara fired on click events, the playing the audio works just fine but it doesn't stop with the call of Pause function.

### Reproducible Example

-

### Reproduction Steps

-

### Possible Solution

-

### Context

I am trying to build a custom music player with react (Nextjs).

### Howler.js Version

v2.2.3

### Affected Browser(s)/Versiuon(s)

chrome

**Comment by lustremedia** [comment] 2022-01-26 10:23
Did you try to pause it with an ID?  
`const id = sound.play()`     then 
`sound.pause(id)` 

Maybe there might be an issue with sound being a const?

**Comment by OdapX** [comment] 2022-01-26 15:30
I tried that but it doesn't work either , really don't know what causing this,

**Comment by lustremedia** [comment] 2022-01-26 15:40
Your `const Pause` is capitalized, is that on purpose? However this is not a bug for sure but more like a debugging issue in your app. You should move that to discussions .... https://github.com/goldfire/howler.js/discussions  and close this issue

**Closed** 2022-01-26 15:51 UTC
Labels: bug

**Comment by suterma** [comment] 2022-01-27 07:19
> Did you try to pause it with an ID? `const id = sound.play()` then `sound.pause(id)`

Late, but to clarify: As long as there is just one Howl, Id's are not necessary to use. I do this all the time, since I have only one sound at at time (also doing some kind of music player): https://github.com/suterma/replayer-pwa/blob/3b624091a035e8d4b94db6c81039a581b6d1a59d/src/components/TrackHowlerPlayer.vue#L350
