### ISSUE TITLE
Using loopStart and loopEnd

### ISSUE THREAD

**Issue by javismiles** [goldfire/howler.js#361] opened 2015-10-11 18:10 UTC
Good day, i love this library,
how can i use loopStart and loopEnd values with howler.js?
they are the only way i have found to produce great gapless loops with the web audio api and would love to use them with your library 
thank you :)

**Comment by goldfire** [comment] 2015-10-13 02:50
Closing as duplicate of #360.

**Closed by goldfire** 2015-10-13 02:50 UTC

**Comment by javismiles** [comment] 2015-10-15 14:34
just to clarify, are loopStart and loopEnd parameters being added to next version of Howler, whose release date is still unknown, correct?
