### ISSUE TITLE
Chrome Tab muting ignored by Howler?

### ISSUE THREAD

**Issue by mwkcoding** [goldfire/howler.js#1511] opened 2021-08-27 07:26 UTC
I've noticed when I use howler.js for playing audio (not sure if it's the JS Audio API or howler.js specifically) that if a tab is muted audio plays anyways literally ignoring the tab mute?
This might be a Chrome bug but I've found nothing about it and I'm pretty sure people would've submitted bug reports about it already.
I have not noticed it anywhere else. Only with howler.js on my site.

System Info:
MacOS Big Sur 11.4
Google Chrome Version 92.0.4515.159 (Official Build) (x86_64)
Howler.js 2.2.3

**Comment by drittich** [comment] 2021-08-31 18:07
I'm also experiencing this issue. A previously muted Chrome tab plays audio sometimes.

**Comment by celinekurpershoek** [comment] 2021-09-23 11:46
I have the same issue
MacOS Big Sur 11.2.1
Version 94.0.4606.54 (Official Build) (x86_64)
Howler 2.2.0

Issue is not there in Firefox

**Comment by JLMonk** [comment] 2021-09-29 15:48
I'm having the same issue on Chrome. Have been for a few months at least.

**Comment by goldfire** [comment] 2021-11-28 20:51
Does anyone have a reproducible case? I've been unable to reproduce this on any of the demos or on our games that use howler.

**Comment by drittich** [comment] 2021-11-29 16:35
I tried to reproduce on the same code base as before and I can't. I suspect something in Chrome has changed.

**Comment by goldfire** [comment] 2021-11-30 15:06
Okay, thanks for the confirmation. I'll close this for now, but if someone is able to repro it again I'll reopen.

**Closed as completed by goldfire** 2021-11-30 15:06 UTC

**Comment by jslavens-mvrk** [comment] 2021-12-01 17:46
@goldfire We've also been running into this issue in one of our projects. We have background music on our site and I've been developing with the Chrome tab muted. 

System info:
- MacOS Monterey 12.0.1
- Chrome Version 94.0.4606.71 (Official Build) (x86_64)
- Howler 2.2.3

Unfortunately I can't share the project code, but here are some things I noticed that might help narrowing the issue down:
- We're using Vite for bundling, and every once in a while a hot reload will trigger the music to play even though the tab is muted
- The bug happens pretty consistently when my computer is asleep and I unlock it
- The bug has happened _while my computer is locked_ when I accidentally clicked my mouse

I just set `Howler.autoUnlock = false;` today to see if that fixes the issue and I haven't run into it yet so that might be a contributing factor?
