### ISSUE TITLE
elusive audio distortion bug ,because audioContext init is not expected correctly for the sampleRate is not set right  on IOS

### ISSUE THREAD

**Issue by underbayan** [goldfire/howler.js#434] opened 2016-01-26 05:08 UTC
i also found a solution for this ,you can get answer here :https://github.com/Jam3/ios-safe-audio-context

**Comment by makdas** [comment] 2016-01-26 09:04
Are these issues related? 
https://www.scirra.com/forum/viewtopic.php?f=147&t=165414&p=1005298#p1005298

**Comment by nhoizey** [comment] 2016-01-26 10:50
I have had also an issue with audio completely distorted on iOS, when running in [the PhoneGap port](https://github.com/esviji/esviji-phonegap) of my game [esviji](http://esviji.com/).

I'm currently using Howler.js 2.0.0 beta 7.

**Comment by makdas** [comment] 2016-01-26 11:02
Im also using howler but v1.1.29....  Are you having distortion on first launch of the app or any launch thereafter?

**Comment by nhoizey** [comment] 2016-01-26 12:55
Never on first launch, it seems, more after a while, after having switched to other apps momentarily.

**Comment by DFortun81** [comment] 2016-01-27 20:09
I have experienced this as well - one way I fixed this was to use appcache to explicitly tell the browser to always redownload the audio assets. This is an awful solution as it also means that the data usage goes up significantly for frequent users, but it fixed the problem where the sounds were all barbled with a really low bit rate.

Something else to note: Sounds that were not played before did not encounter this problem, only sounds that had previously been loaded. I'm not sure if they were also played, but the action of downloading them and then reloading the context where the asset would be cached causes this problem. I would bet this is a low level (obviously something outside of HowlerJS's jurisdiction) recovery problem where the bit rate variable is not saved with the audio asset, or it is, but it's ignoring the value.

**Comment by makdas** [comment] 2016-01-28 08:02
Thanks @DFortun81 , can you give me a snippet of how you implemented appcache? I also found that clearing the cache or using web inspector to refresh the app solved the problem

**Comment by DFortun81** [comment] 2016-01-29 14:58
Here's a sample appcache that I have for an example project for my coworkers. I have 3 graphics assets, a couple of audio files, and a bunch of javascript. I only want to cache the graphics assets for mobile. JavaScript can have frequent changes and so having those assets cache could have extremely bad effects on our game(s). 

```
CACHE MANIFEST
# 2016-01-29 v1.0.0
CACHE:
icon.png
background.png
mycachedimage.png
NETWORK:
*
FALLBACK:
```
In your HTML file(s), set the html manifest like so:
```
<!DOCTYPE html>
<html manifest="cache.appcache">
	<head>
		...
```


Using JavaScript, use the updateready event to reload the page context: (otherwise appcache does absolutely nothing)

```
// Check for an update to the application cache.
var appcache = window.applicationCache;
if(appcache) {
	appcache.addEventListener('updateready', function() {
	  appcache.swapCache();  // The fetch was successful, swap in the new cache.
	  window.location.reload();
	});
}
```

NOTE: If you are building your website for both desktop and mobile, make a mobile subdomain that only caches the graphics and have the desktop version also cache the audio as it doesn't have this problem.

**Comment by goldfire** [comment] 2016-01-29 20:07
Can anyone confirm if https://github.com/Jam3/ios-safe-audio-context fixes the issue? It would be trivial to implement into howler.js if so. Also, does this only happen in something like PhoneGap/Cordova or can it be replicated in the browser (I've been unable to replicate in browser, but maybe I'm doing something different).

**Comment by DFortun81** [comment] 2016-01-29 20:13
@goldfire I have not tried that particular hack yet, but I can pretty quickly merge it with my local copy to test if it works. I'll edit when I have completed my test.

**Comment by patrickfabrizius** [comment] 2016-02-01 10:40
I have the same issue (Howler 1.1.26 though) and the ios-safe-audio-context-fix didn't work for me. Unless there's something that's been fixed in Howler itself since 1.1.26 that could cause the problem, the fix doesn't work.

**Comment by patrickfabrizius** [comment] 2016-02-01 12:02
Pattern seems to be: 
* Clear cache in Safari settings
* Open Safari and your webapp (sound works)
* Reload Safari (sound works)
* But if you close Safari and open again (sound is distorted each time). 
Could it be something with the cache as someone suggested?

**Comment by DFortun81** [comment] 2016-02-01 15:33
The problem seems to have come back this morning. Not too sure why it was working flawlessly on Friday and Saturday after we put in that hack.

**Comment by patrickfabrizius** [comment] 2016-02-01 15:37
@DFortun81 can you confirm that my pattern holds?

**Comment by DFortun81** [comment] 2016-02-01 15:44
@patrickfabrizius That was most definitely related to how it worked. **Settings -> Safari -> Clear History And Website Data** to clear the browser cache for Safari.

It seems as though the problem this morning isn't related to the hack. None of my code after the hack is run seems to be executing. Perhaps a null reference? I need to do some debugging. Will comment shortly.

**Comment by makdas** [comment] 2016-02-02 07:35
hi, is there an example of the hack being implemented into howler?

**Comment by goldfire** [comment] 2016-02-05 18:54
Does anyone have a basic test-case with reproducible steps?

**Comment by patrickfabrizius** [comment] 2016-02-05 19:01
@goldfire I think you can take anything that uses Howler and then run thru the steps I've described above, it should highlight the problem.

**Comment by goldfire** [comment] 2016-02-05 19:22
@patrickfabrizius Sorry, didn't see you had updated that post. I hadn't been force closing Safari, which is why I hadn't been able to get it to work until now. You can force HTML5 audio by setting `buffer` to `true` on 1.x and `html5` to `true` on 2.0.

**Comment by goldfire** [comment] 2016-02-05 19:35
Using 2.0 I'm able to consistently fix this issue by immediately calling `Howler.unload()` before setting up any new sounds. This destroys the current context and creates a new one, with the new one having a correct `sampleRate` of 44100. This is similar to what the above hack seems to be doing. Can anyone else confirm the same thing (the global unload is only on the 2.0 branch)?

**Comment by davidfig** [comment] 2016-02-06 02:05
Based on my initial tests, adding the Howler.unload() before loading sounds fixed the distortion for iOS. I'll chime back if this changes with further testing.

Thanks for the working on this. This has been an annoying bug.

**Comment by viniciusbo** [comment] 2016-02-17 19:59
`Howler.unload()` before loading sounds worked for me too.

**Comment by davidfig** [comment] 2016-03-08 22:59
I came across a rare situation where after switching and then resuming an iOS Cordova app, the sound becomes distorted again. I haven't been able to reliably repro it, but I have heard it a few times. I expect it's related to this bug. 

I was thinking of unloading and then reloading all the sounds on app resume. Anyone else experience this?

**Comment by JenGL** [comment] 2016-03-17 11:22
@goldfire I had this Iusse to and Howler.unload() fixed the problem!
I'll keep in touch to contact you if the problem will be raised again

**Comment by metalim** [comment] 2016-03-23 09:46
Doing Howler.unload() just before creating Howls mutes everything for me, as previously unlocked autio context gets locked again. My task requires loading Howls after audio is unlocked: there is simple Yes/No question to the user, that unlocks audio context. Any suggestions?

Also, was anyone able to solve iOS audio distortion by calling ctx.createBuffer(1, 1, 44100) instead of ctx.createBuffer(1, 1, 22050) in unlock function?

**Comment by goldfire** [comment] 2016-03-26 20:57
The unload is now included automatically on mobile with this commit: cb948c8a54fe19ef2d0bc177f464b21cad09d261.

**Closed by goldfire** 2016-03-26 20:57 UTC
