### ISSUE TITLE
The web audio autoplay policy re-enabled in Chrome 70...

### ISSUE THREAD

**Issue by dotMastaz** [goldfire/howler.js#1014] opened 2018-08-07 13:31 UTC
Here for the detail :
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

Do you have a plan for this ?

Thank you for your work !!

**Comment by antag0n1st** [comment] 2018-08-28 09:42
Any way to fix this one ?

**Comment by goldfire** [comment] 2018-09-07 19:39
Closing as duplicate of #939.

**Closed by goldfire** 2018-09-07 19:39 UTC
