### ISSUE TITLE
Android WebView

### ISSUE THREAD

**Issue by tomasz-swirski** [goldfire/howler.js#480] opened 2016-03-22 12:30 UTC
I've got problem with controlling sound played in android webview.
My code looks (exactly) like this:

var s = new Howl({src: 'test.mp3'});
$(document).on('click', function(){ s.play; });

And at this point when anything within webview is clicked the sound starts playing.
Also calling s.seek() returns correct value...
However those doesn't work s.pause(),  s.stop(), s.seek(secs);
I've testes this with and without sound ID returned from .play() but that makes no difference.
I've tried mp3 and webm formats and both html5: true and html5: false

My Android version is 4.4.4 on Asus Nexus7

**Comment by goldfire** [comment] 2016-03-26 20:09
I'm not able to reproduce this on my end. How long is the audio file you are testing with?

**Comment by tomasz-swirski** [comment] 2016-03-29 08:34
The reason for this behavior is wrong  duration value ( === 0) insinde this condition:

      // Create a timer to fire at the end of playback or the start of a new loop.
      var timeout = (duration * 1000) / Math.abs(sound._rate);
      if (timeout !== Infinity) {
        self._endTimers[sound._id] = setTimeout(self._ended.bind(self, sound), timeout);
      }

the _ended function sets .paused to true, and  .stop(), .pause() and and .seek() checks for this flag and retuns if sound is paused. therefor those functions wont work

Solution is to change onend triggering method and relay on html5 AudioObject .onended callback like this:

 if(self._webAudio){
        // Create a timer to fire at the end of playback or the start of a new loop.
        var timeout = (duration * 1000) / Math.abs(sound._rate);
        if(timeout !== Infinity) {
          self._endTimers[sound._id] = setTimeout(self._ended.bind(self, sound), timeout);
        }
      } else {
        sound._node.onended = self._ended.bind(self, sound);
      }


Best regards

**Comment by goldfire** [comment] 2016-04-08 21:46
Closing as duplicate of #482.

**Closed by goldfire** 2016-04-08 21:46 UTC
Labels: android
