### ISSUE TITLE
Fade In => Fade Out

### ISSUE THREAD

**Issue by DFortun81** [goldfire/howler.js#363] opened 2015-10-12 19:42 UTC
If you attempt to fade out a howl and then immediately fade it back in while the fade out is still active, both fades happen at the same time and you get gittery sound until both fades have completed.

Recommended solution: Replace the setTimeout silliness with a window.setInterval and window.cancelInterval when fade is invoked again.

**Comment by goldfire** [comment] 2015-10-16 18:43
This is already how the 2.0 branch handles it, you just can't stop it yet. Closing as duplicate of #355.

**Closed by goldfire** 2015-10-16 18:43 UTC
