### ISSUE TITLE
"buffering" with the Web Audio API

### ISSUE THREAD

**Issue by agentfitz** [goldfire/howler.js#554] opened 2016-06-25 16:40 UTC
I know from reading the Howler docs that `html5` is intended to be used for "longer audio files." I am finding using the html5 flag to be problematic (not necessarily because of howler, but because of the state of html5 audio vs. the state of the Web Audio API). I've noticed:

- unexpected errors claiming "the user must explicitly take an action to play back audio," which he did
- unexpected firing of events
- unsupported playback speed adjustment with rate()

Long story short, I would prefer to use the Web Audio API implementation (via Howler), rather than the html5 audio implementation, but my app makes use of "longer audio files." So this is my question: _is the (lack of) buffering support for longer audio files a limitation of the Web Audio API itself or a limitation of Howler_?

Is there any hope of adding "buffering" support to the Web Audio API implementation of Howler any time soon? If not, does anyone know of a way to get some sort of "download progress" event so I can at least show a `percentage loaded` indicator for my users while they wait for the full audio file to download?

Thanks for any insight.

**Comment by goldfire** [comment] 2016-06-25 16:52
The way Web Audio works, you must wait for the full audio file to download through XHR, it then must be decoded by the browser, and then you can begin playback. I'll be looking to add a standardized progress event soon after 2.0 is released (we are already at a release candidate, so no more API changes or additions will be made at the moment).

To be clear, all of the issues with HTML5 Audio you describe are strictly related to Chrome on Android or the stock Android browser. It should work fine virtually anywhere else.

**Comment by goldfire** [comment] 2016-06-25 16:52
FYI: Closing as duplicate of #489.

**Closed by goldfire** 2016-06-25 16:52 UTC
