### ISSUE TITLE
[2.0b12] howler.core.js:71 Uncaught TypeError: Cannot read property 'gain' of null

### ISSUE THREAD

**Issue by Willian-Zhang** [goldfire/howler.js#517] opened 2016-05-07 13:44 UTC
``` javascript
        self._volume = vol;

        // When using Web Audio, we just need to adjust the master gain.
        if (Howler.usingWebAudio) {
  >        Howler.masterGain.gain.value = vol;
        }
```

**Comment by goldfire** [comment] 2016-05-07 16:26
Closing as a duplicate of #511. If you have a test case to reproduce this that would be hugely useful.

**Closed by goldfire** 2016-05-07 16:26 UTC
