### ISSUE TITLE
InvalidStateError: Failed to execute 'stop' on 'AudioBufferSourceNode'

### ISSUE THREAD

**Issue by maxime-crunding** [goldfire/howler.js#226] opened 2014-10-16 15:02 UTC
I got this error sometimes: 

** Uncaught InvalidStateError: Failed to execute 'stop' on 'AudioBufferSourceNode': cannot call stop without calling start first. **

I can reproduce it when I try to play/stop multiple sounds at the same time.
I'm on osx with Chrome Version 39.0.2171.27 beta (64-bit)

Any suggestion?

Related to this:
 Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': Duration must be a finite non-negative number: -1.12327
- Howler.js: line 506.

**Comment by goldfire** [comment] 2015-02-03 18:22
These issues should be fixed in the 2.0 branch, but please let me know if you are still seeing them.

**Closed by goldfire** 2015-02-03 18:22 UTC

**Comment by arya-s** [comment] 2016-05-25 02:39
I can reproduce this on mobile devices with a button that is used for playing/pausing audio. If I spam this button I get into these two states:

```
howler.min.js:2 Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': The duration provided (-0.17) is less than the minimum bound (0).f @ howler.min.js:2t.play @ howler.min.js:2button.onclick @ lm_bundle.js?dc32441…:45935
howler.min.js:2 Uncaught InvalidStateError: Failed to execute 'stop' on 'AudioBufferSourceNode': cannot call stop without calling start first.
```


Here's a the code to reproduce this:

```
var sound   = new window.Howl({src: '/media/audio/accessible_uWSKjgX.mp3'});
var button  = document.createElement('button');
button.textContent = 'Play';
var playing = false;

button.onclick = function () {
   playing = !playing;

   if (playing) {
      sound.pause();
   } else {
      sound.play();
   }
};

sound.on('end', function () {
   playing = false;
 });
```

**Comment by goldfire** [comment] 2016-05-27 21:20
@arya-s Can you give some more details on how you got that to happen including your testing environment? I setup the following fiddle and was unable to reproduce: https://jsfiddle.net/c9ezqbqj/.

**Comment by arya-s** [comment] 2016-06-01 01:40
@goldfire it doesn't work with a fiddle, unless you know a way to disable zoom on double tap. You need to spam tap this button.

**Comment by fabioelia** [comment] 2016-11-10 20:50
Ran into the same issue on our application today.
Flooding the play action with numerous requests can lead to this problem, where the seek and duration can be returned as negative

**Comment by ofirgeller** [comment] 2017-02-27 22:28
Got this with version 2.0.2 (happened to a user). 

Tried to replicate by spamming the play-stop button both on desktop and android.

Did not result in an error.

**Comment by fraktalfabrik** [comment] 2019-08-15 07:51
Getting it with 2.0.5
