### ISSUE TITLE
Load 23mb mp3 file (audio sprites) crash mobile

### ISSUE THREAD

**Issue by neophob** [goldfire/howler.js#1151] opened 2019-03-22 23:01 UTC
I load a 23mb audio sprite mp3 file in the browser - that works fine in desktop browsers but crash on my mobile (ios 12.1.4, Safari and Chrome).

for testing I enabled html5 mode - it did not crash the mobile browsers anymore but was unusable with audio sprites. The crash happens as soon as the data is loaded. A live issue can be discovered on https://playfield.dev/ when you select the game "Fishtales".

So I assume a memory issue, one thing which can be done is reducing the quality of the audio file. any other hints how to reduce the memory footprint for mobile phones?

**Comment by neophob** [comment] 2019-03-25 20:23
Note: also reducing the mp3 file size or change the encoding does not help, so I assume the problem is the uncompressed data

**Comment by neophob** [comment] 2019-03-25 22:41
If you use a large audio sprite file, howler will load and decode the whole file into memory. Depending on the file of the audio sprite file - this will crash a mobile browser (i have a 45 minutes mp3 file).

Also the inactive pool size won't really help, as my mobile browser crash as soon as the loading of the audio file is finished and the onEnd event is fired.

Any idea how to resolve this issue?

**Comment by st-h** [comment] 2019-03-30 15:54
@neophob I think your observations regarding web audio are correct.  The whole file is loaded into a buffer before it can be played. I have been able to play back files with a duration over an hour on desktop that way, however with the limited memory available on mobile devices, this can quickly lead to issues. Usually the issue is the amount of memory the decoded mp3 file requires. If you increase compression etc, this only reduces the size of the mp3 - not the decoded stream you are trying to actually play back.
With html5 enabled a html `<audio>` element is used to play back the file instead of the buffer. The browser usually makes range requests to the server to load the parts of the file that are currently required. This works a lot better when the available memory is limited. 
So far I have spent quite some time trying to figure out various issues I came across when trying to play back audio through an audio element on macOS/iOS (things like audio not playing even the browser tab shows the speaker icon and the Touch Bar displaying progress, or occasional noises), but unfortunately haven't been able to find anything other than a few related posts on the web without any resolution - and a few possibly related webkit bug reports. Sorry that this won't help with your actual issue, as I am looking for a way to resolve these issues myself.

**Comment by st-h** [comment] 2019-03-31 14:01
@neophob If you want to use the html5 audio element, you should make sure that your server handles range requests correctly. If not, there usually are issues when seeking within a file, which could relate to the issues you are describing. 
You can find some information about range requests and how to check here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

**Comment by darren-dev** [comment] 2019-04-12 07:47
@neophob Please close this issue if you've found a solution, or provide more details.

**Closed** 2019-04-19 17:55 UTC

**Comment by TimMorrisDev** [comment] 2021-07-23 13:39
was a solution to this found? I'm struggling with the same issue now

**Comment by TimMorrisDev** [comment] 2021-07-24 13:20
was a solution to this issue ever figured out? I'm having this problem in a project I'm working on

**Comment by Diex** [comment] 2022-05-24 19:48
the solution is to use howler in html:true mode.
this way you get 206 responses (instead of 200 after the whole file is downloaded)
however it takes you to the problem that web audio api won't work.
any thought?
