### ISSUE TITLE
Suggestion? - Option to have '.rate' only change playback speed instead of pitch.

### ISSUE THREAD

**Issue by Bluhman** [goldfire/howler.js#1522] opened 2021-09-29 21:05 UTC
I'm attempting to use the howler library to implement a custom audio player for listening to transcribed conversations. I want the option to fast-forward through the conversation to a point of interest, but I found that the way howler is speeding the audio up is just by playing the sound back at a higher frequency (i.e. just compressing the waves into shorter ones to that they then sound higher pitch, and are also faster.)

Would it be possible to implement a setting on the howl model that allows us to pick whether to have the 'rate' affect sound pitch? Something like a ['time-stretching' setting](https://en.wikipedia.org/wiki/Audio_time_stretching_and_pitch_scaling).

For my current purposes I bet there's some way I could juryrig it to work the way I'd want it (the audio player includes an interactive timeline users can click on to seek across the audio. If they do this from start to end, slices of the audio can be heard playing back faster but still at the same pitch, which is essentially the effect I want to achieve with howler) so if anyone's got advice on how I can do that, that'd also be greatly appreciated.

**Comment by goldfire** [comment] 2021-11-28 20:54
Duplicate of #586.

**Closed by goldfire** 2021-11-28 20:54 UTC
