### ISSUE TITLE
[2.0, iOS] occasional distorted play back

### ISSUE THREAD

**Issue by branaway** [goldfire/howler.js#488] opened 2016-03-27 03:21 UTC
I have got occasional distorted playback of sound. The same html page would render fine most of the time, but would gave occasional distorted sound. But I could not pinpoint to a use case where I could reproduce it. 

Not sure if this was related to Howler, but I thought I'd report anyway.

**Comment by goldfire** [comment] 2016-03-27 16:12
This is most likely a duplicate of #434.

**Closed by goldfire** 2016-03-27 16:12 UTC
