### ISSUE TITLE
Chrome Android local files not playing

### ISSUE THREAD

**Issue by MrGlasspoole** [goldfire/howler.js#484] opened 2016-03-23 17:58 UTC
Hi,

just found out about howler and it's great.
My problem is that i can't play local sound files in Chrome on Android.
I know it has to do with same origin policy - but from reading it should be possible with the "buffer" setting?

Firefox plays the local sound files but in bad quality and i need Chrome because i need to run my HTML/JS in full screen as "web app".

These are just a view files for a home automation touchscreen and i don't want do install a full HTTP server for that.

And is there something like howler out there in the wild web for videos?

**EDIT**
It seems like there is no way playing local files in Chrome on Android.
So i started learning Android Studio and after a view hours it works.
I have the files in a folder and this:
`var evil = new Howl({urls: ['/storage/sdcard0/sound/evil-laugh.wav']});`
plus this in the AndroidManifest.xml:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
does the magic.

**Comment by goldfire** [comment] 2016-03-26 20:06
Awesome, thanks for the update!

**Comment by MrGlasspoole** [comment] 2016-03-26 22:08
Maybe you can clarify some things for me. I came across Cordova and they have this plugin:
https://github.com/floatinghotpot/cordova-plugin-nativeaudio

The name says "native" but the roadmap is confusing:
> is as fast and feature-rich as native mobile APIs
"is as" to me means it is not native.
And they write:
> Currently, neither HTML5 Audio or the more recent Web Audio API offer a cross-platform solution which 1) is fast, 2) supports polyphony, 3) concurrency and 4) maintains a low overhead.
If i only need Web Audio API i guess howler is just as well?
Because i can't figure out how to play sound with this plugin and howler v1 just works (v2 does not work in Cordova).

**Comment by goldfire** [comment] 2016-03-27 23:52
I'm not sure what they are referring to, Web Audio API is indeed fast and taps into native control of sound. Also, our howler.js samples for 2.0 are working without any issues in Cordova, what aren't you getting to work?

**Comment by MrGlasspoole** [comment] 2016-03-28 06:29
If i load v2.0.0.min instead of v1.1.29.min and changing url to src then sound stops working.
This works with v1 but not v2:
```
var auf = new Howl({src: ['/storage/sdcard0/GertyTouch/audio/aufgebaut.mp3']});
var sound = document.getElementById('audioTest');
sound.addEventListener('click', function(e) {
  e.preventDefault();
  auf.play();
});
```
Whats the difference between the normal min, core.min and effects.min?

And is there a easy way to play one sound after the other?
I'm building a front door bell that speaks and i don't want to make a sound file for everything.

**Comment by goldfire** [comment] 2016-03-28 16:09
Have you tested that with beta9?

**Comment by goldfire** [comment] 2016-04-08 21:44
Closing for now as I'm still unable to reproduce the reported issue. Will reopen if more details to reproduce are provided.

**Closed by goldfire** 2016-04-08 21:44 UTC
Labels: android
