### ISSUE TITLE
Dolphin 11.5.4 plays only first sec of audio file.

### ISSUE THREAD

**Issue by tomasz-swirski** [goldfire/howler.js#467] opened 2016-02-26 13:52 UTC
Dolphin 11.5.4 plays only first sec of audio file.

**Comment by goldfire** [comment] 2016-02-26 16:37
Which version of howler.js are you using?

**Comment by tomasz-swirski** [comment] 2016-02-28 23:13
recent from 2.x repo ;)

**Comment by tomasz-swirski** [comment] 2016-02-28 23:17
However both howlers (1.x and 2.x) do the same thing. 
Inline html <audio> works fine though.

I've noticed that calling .play() multiple times makes sound finally play but then calling .stop() or pause() fails...

**Comment by goldfire** [comment] 2016-03-11 20:16
Are you having the issue when setting html5 to true so that it directly compares HTML5 audio rather than Web Audio vs HTML5 audio? That would at least help narrow things down.

**Comment by tomasz-swirski** [comment] 2016-03-30 09:36
Solved.  Wrong duration value passed to onEndTimer which fired too soon.
Fix is to relay on onending event of Audio object when woring in html5 mode.

Best regards

**Comment by goldfire** [comment] 2016-04-08 21:45
Closing as duplicate of #482.

**Closed by goldfire** 2016-04-08 21:45 UTC
