### ISSUE TITLE
Cashing issues, sound distort

### ISSUE THREAD

**Issue by makdas** [goldfire/howler.js#433] opened 2016-01-25 09:31 UTC
Im using howler.js for my sound framework in my html5 apps. Whenever i run my app for the first time i have no sound issues. After killing the app and opening it a second time, my app sound get distorted, which tells me its something to do with the browser wrapper cache. The only way i can get my sound back to normal is by using the refresh button on the safari web inspector.
I'm pulling my hair out over this issue. Please Help ;(

**Comment by goldfire** [comment] 2016-01-29 19:47
Closing as duplicate of #434 as the discussions appears to have centered there (if these are actually two separate issues let me know and I'll re-open).

**Closed by goldfire** 2016-01-29 19:47 UTC
