### ISSUE TITLE
Loop/Multiple Playback Broken Chrome Canary 42.0.2303.3 canary (64-bit)

### ISSUE THREAD

**Issue by motopete** [goldfire/howler.js#279] opened 2015-02-13 04:24 UTC
It appears the latest beta version of Howler2 doesn't work in the latest version of Chrome Canary (Version 42.0.2303.3). When playing a sound with 'loop: true' option, it only plays the first iteration - and does not loop. After that, any subsequent call to Play() results in no response also, until the page is reloaded.

**Comment by goldfire** [comment] 2015-02-15 19:01
I am able to reproduce, but it is clearly a bug in the development build. We should continue to track it to make sure the bug doesn't make its way to stable Chrome.

**Comment by SpaceK33z** [comment] 2015-03-30 11:00
Hm, this bug has made it's way into Chrome Beta (42.0.2311.60) and is also present in Chrome 43.0.2350.0 (canary).

**Comment by Rob--W** [comment] 2015-03-30 11:47
I ran a bisect, and found two commits in Blink to blame.

- This commit completely broke loop, i.e. no audio is played back at all: https://chromium.googlesource.com/chromium/blink/+/1053d1f0d2ca8bf2b5d4effc58168054dd47f87c (rolled in version 42.0.2297.0, https://chromium.googlesource.com/chromium/src/+/34c9927ecbd4dc8c477cb79e91e887792779fc11)
- This commit enabled audio again, but the loop is not working (i.e. the audio is played once and not repeated): https://chromium.googlesource.com/chromium/blink/+/bac93bd1432d1f299e4aa6849de1c5745f58f550 (rolled in version 43.0.2321.0, https://chromium.googlesource.com/chromium/src/+/3fce3419cc2fb19a60651d31e5ae94deeb663979)

Is this a bug in Howler, or a bug in Chrome? If the latter, it would be nice if someone creates a reduced example and reports the bug at https://crbug.com/new and shares a link here.

**Comment by Rob--W** [comment] 2015-03-30 14:12
This is now a bug in Howler. Chrome's behavior has been updated to match the behavior of the latest Web Audio spec (https://github.com/WebAudio/web-audio-api/issues/421), which means that if duration is set, audio playback stops after `duration` time has elapsed (https://github.com/goldfire/howler.js/blob/c5a5cf63cf0439deb6dbbaba857e7fa86ab86905/src/howler.core.js#L503).

**Comment by jayther** [comment] 2015-04-15 22:26
This issue is now in the release version of Chrome.

**Comment by ahumphreys87** [comment] 2015-04-16 11:26
We've fixed this in our app by catching the end event and replaying:

```
sound._onend[0] = function() {
  sound.play();
};
```

This works for us as we don't manually stop these sounds - might need a bit more tweaking for those that manually stop looping sounds.

**Comment by Baccanno** [comment] 2015-04-17 13:35
:/ not ideal at all indeed

**Comment by Baccanno** [comment] 2015-04-17 14:05
our hack 

```javascript
               //use loopHack instead of loop();
               Howl.prototype.loopHack = function() {
                    this._loopHack = true;
                };
                params.onend = function() {
                    if ( this._loopHack ) {
                        this.play();
                    }
                }
                var music = new Howl( params );
                if ( params.loop ) {
                    music.loop( false );
                    music.loopHack();
                }
```

**Comment by goldfire** [comment] 2015-04-17 18:00
Thanks everyone for the details, I'm seeing the issue as well and am digging around to see what can be done in the library itself.

**Comment by goldfire** [comment] 2015-04-17 19:33
The only solution I've been able to find that works in every scenario I tested is to set a very high duration when looping. I've included this in commit: https://github.com/goldfire/howler.js/commit/7d8ad4cf227573e10cf1afe0b97e6e9b8eafca81.

I'm going to go ahead and leave this open for now in case anyone finds any unintended side effects from this change.

**Comment by wittnl** [comment] 2015-04-17 19:58
Not sure if this would be a better solution, but similar to @ahumphreys87 solution, I used `sound.pos(0)`in my onend event handler. Should be able to replace that with the start time of a sprite as well if my understanding is correct. Tested for both HTML5 and WebAudio.

**Comment by goldfire** [comment] 2015-04-17 20:01
@wittnl That is essentially how it works when using HTML5 Audio, so if the above solution ends up having other issues then we can easily switch to using that across the board. The assumption is that Web Audio's built-in looping should technically work better, though it is hard to say if that is actually the case in practice or not.

**Comment by underscorediscovery** [comment] 2015-04-18 01:34
This is also (obviously) affecting the stable releases of Howler in practice :)

**Comment by wmodes** [comment] 2015-04-18 19:23
This also effects Howler 1.1.25. @goldfire have you committed a fix for the stable 1.x release?

**Comment by cloakedninjas** [comment] 2015-04-21 14:44
+1

**Comment by juanpicado** [comment] 2015-04-21 17:04
I've had issues using higher values with the **duration** parameter in Chrome mobile with my audios, but nevertheless in Chrome desktop works fine. I had to use a range of values 20K to 30K. A double check here would be good.
``````
node.bufferSource.start(0, pos, xxxxxxxxx) 
``````

**Comment by goldfire** [comment] 2015-04-21 22:39
This is now live in the stable branch with v1.1.26. I also lowered the duration to 86400, which seems to have fixed the issue in mobile Chrome in my testing. If for some reason you need to loop a sound for more than 24 hours, you'll need to add in some custom logic to handle that.

**Comment by underscorediscovery** [comment] 2015-04-21 23:44
@goldfire thanks for the 1.1.26 update! 

I'm curious if the duration related stuff is the cause of another issue: the `end` event on looping only happens the first time. I can make a test case if desired, but `onend` in Howl construction, or `howl.on('end'..)` both only fire once on looping sounds with 1.1.25 (at least more recently, as i tested my loop events working on the same version previously).

**Comment by cloakedninjas** [comment] 2015-04-22 09:42
Thanks for fixing :+1:

**Comment by Baccanno** [comment] 2015-04-22 10:55
Seems fixed in my case too. Many Thanks :)

**Comment by goldfire** [comment] 2015-04-22 16:33
@underscorediscovery Do you know if the same issue happens in 2.0? Unfortunately, I fell off a ladder and broke my arm last night, but I'll try and take a look in the next few days once I get used to my left hand.

**Comment by underscorediscovery** [comment] 2015-04-22 18:36
@goldfire ah sorry to hear about that!

I will test on 2.0 and report back. I was holding off on trying 2.0 since I needed a certain level of parity with native audio (which 1.1.25 basically has), but it's a good excuse to help test it overall.

**Comment by vergnes** [comment] 2015-06-10 09:51
@goldfire I have tried on 2.0, it seems to be fixed on Chrome 43.0.2357.124 (64-bit)

**Closed** 2015-06-14 06:47 UTC

**Comment by patrickfabrizius** [comment] 2015-08-12 15:51
I found this thread and updated to 1.2.26 which seems to have solved the problem. However, my audio only seems to loop once?

**Comment by JCarlosR** [comment] 2016-12-04 22:47
Hi. I have the v2.0.2 and when I set the loop property to true the sound never is reproduced (Chrome 54.0.2840.99).
Meanwhile I am using ```onend``` when is needed.
Thanks.

**Comment by goldfire** [comment] 2016-12-05 02:36
@JCarlosR Can you open a new issue with sample code to reproduce the issue?
