### ISSUE TITLE
Add TS types into repository

### ISSUE THREAD

**Issue by kibertoad** [goldfire/howler.js#1205] opened 2019-08-04 11:26 UTC
Would you be interested in the PR that would move types from https://github.com/DefinitelyTyped/DefinitelyTyped into howler repo itself? Usually that makes both maintaining and consuming types more convenient.

**Comment by goldfire** [comment] 2020-06-28 16:34
Closing as duplicate of #1032.

**Closed by goldfire** 2020-06-28 16:34 UTC
