### ISSUE TITLE
Problem with using multiple instances of the same sound 

### ISSUE THREAD

**Issue by Miguel-Barreiro** [goldfire/howler.js#285] opened 2015-02-26 09:48 UTC
when creating more than one instance with the same url the sound quality seems to decay with time. If we continue to play it reaches a point where no more sound is heard.

**Comment by Squize** [comment] 2015-04-23 11:32
I'm having the same issue, the sound starts to distort over time until it's just a wall of noise. I've tried increasing the pool size for common sounds which are used a lot ( i.e. baddies dying, explosions etc. ) but with no joy.

I would revert back to v1 but I changed over to v2 because looping seems to be broken on the current version of Chrome with v1.

**Comment by mtharrison** [comment] 2015-04-23 14:04
I'm having the same problem. But I don't have multiple instances of the same sound. I have several howler objects (each with different URLs) which are played over and over several times. After about 30mins the CPU usage in Chrome hits 100% and then sounds because muffled. And then eventually sound stops playing.

**Comment by mtharrison** [comment] 2015-04-23 14:05
BTW @Squize the looping issue has been fixed now in a new release on the 1.x branch of Howler.

**Comment by mtharrison** [comment] 2015-04-23 16:55
This seems related: https://code.google.com/p/chromium/issues/detail?id=478485&can=1&q=audio&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

The problem goes away if I omit the 2nd and 3rd argument to `AudioBufferSourceNode.start()`

**Comment by Squize** [comment] 2015-04-24 11:10
Hey Matt, that's excellent thanks mate.

After posting yesterday I saw the other thread about looping ( Always the way ) and tried 1.1.26 which did fix the looping, but I still got the corrupted sounds it just took longer for them to kick in than in v2 ( Around the time of thinking "Sweet, it all works again" ).

I'm going to give your fix a go on 1.1.26 and let you know how I got on, thanks again.

**Comment by abrahamian** [comment] 2015-06-11 23:06
@mtharrison , would you mind demonstrating your workaround for the muffled sound/ noise problem? 

I can't find the code you suggest patching in either v1 or v2.

**Comment by Squize** [comment] 2015-06-12 11:13
Oops, I totally forgot to reply to this, sorry. I had no joy either, with 1.1.26 or even reverting back to 1.1.25.

I tried various houseKeeping attempts, everything short of actually unload-ing each sound and setting them to null between levels to reload them again ( Like wise I couldn't find the suggested lines in the src to alter )

On the plus side, my game has been out and tested in beta and no one reported the issue, so it seems like it could just be a Chrome / OS X bug. That's not a great plus I know.

**Comment by abrahamian** [comment] 2015-06-12 22:29
@Squize, were you having this noise problem on desktop Chrome? I've only encountered in on IOS.

**Comment by Squize** [comment] 2015-06-17 18:26
Yes it was desktop, in saying that it doesn't seem to be happening any more on Chrome / OS X 43.0.2357.124 (64-bit).
I'm just assuming it was a Chrome bug, as the issue never arose on Safari.

**Comment by goldfire** [comment] 2015-10-02 18:53
Closing this as it appears to have been a browser bug that is now resolved and I haven't been able to reproduce. If you are still seeing this, please pos sample code and I'll reopen.

**Closed by goldfire** 2015-10-02 18:53 UTC
