### ISSUE TITLE
Audio doesnt play if i set html5 to true and audio doesnt play on background if i set html5 to false, Iphone latest ios version

### ISSUE THREAD

**Issue by AashirBhusal** [goldfire/howler.js#1721] opened 2024-04-28 10:27 UTC
### The Problem

Audio doesnt play if i set html5 to true and audio doesnt play on background and only plays on safari if i set html5 to false. it was working fine before by setting html 5 to true but suddenly updated to new ios version and now the audio doesnt play at all. how do i fix this and make it so like before it plays and also plays background its huge headache.

### Reproduction Steps

set html 5 to true and play audio on safari with 17.4.1 ios version. 

### Possible Solution

dont know

### Howler.js Version

latest

**Comment by betanyeli** [comment] 2024-04-29 07:52
Same issue here. Seems to be related to this issue https://github.com/goldfire/howler.js/issues/1711
Check the workaround proposed here while the lib solves the problem

**Comment by Supplementing** [comment] 2024-04-30 15:48
Im also having the same issue. Audio has worked fine for years with my app but as of a recent iOS update, it is no longer playing as intended. FWIW, im using Ionic & capacitor which renders a webview that the audio is being played inside of.

**Comment by Timtam** [comment] 2024-05-07 13:01
Having the same issue here. For some weird reason I can't get html5: false to work under Chrome on desktop nor iOS, so I guess i'm doing something wrong here. Basically creating the Howl with src and format the same way it works with html5: true, then set volume and hit play(), but that doesn't play. How do you make it work under Desktop + iOS?

**Comment by mischa78** [comment] 2024-05-07 13:05
@Timtam I did this to only use `html5: false` on iPhone with iOS 17.4:

    html5: /iPhone OS 17_4/.test(window.navigator.userAgent) ? false : true,

**Comment by Timtam** [comment] 2024-05-07 13:09
Interesting, I'll have to try if that works on iOS but it certainly doesn't work on other browsers if html5 is false. As a side note, for some weird reason, the old playback behaviour on iOS 17.4.1 still works for me with really short files (about 200 kb each and just 3 seconds long). A huge file (at least 2 minutes long and more) doesn't work though, and as far as I can see the state remains at "unloaded" all the time, or something like that (don't know about the Howler internals yet).

**Comment by AashirBhusal** [comment] 2024-05-07 21:58
the issue is similar to #1711 but the fix doesn't apply to me, waiting for official fix

**Comment by Timtam** [comment] 2024-05-08 06:05
You are right, I found it just an hour before your message came in. I successfully switched to the @catalogworks/howler.js branch with html5: true and it fixed it in my use-case. It'd be great to have an official release which addresses this issue at some point, but its better than nothing for sure.

**Comment by jamesharding** [comment] 2024-05-15 15:26
Seems to be fixed in iOS 17.5 for me!

**Comment by AashirBhusal** [comment] 2024-05-16 04:22
yup its fixed its working correctly for me now.

**Closed** 2024-05-16 04:22 UTC
Labels: bug
